# Exercises with Python




https://docs.python.org/

https://docs.scipy.org/doc/numpy/




In [1]:
import numpy as np

## Numpy
### Exercise 1
#### Creat an array of 450 random integers between -10 and 10

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

In [2]:
array = np.random.randint(low=-10, high=10, size=450, dtype='int')

array

array([ -7,   9,  -3,  -7,   5,   0,   9,   2,   7,   9,   9,   4,   7,
         0,  -1,   2,  -3,  -1,  -6,  -7,  -2,  -1,  -3,  -4,   6,   3,
        -5,   7,  -1,  -5,  -8,  -7,  -8, -10,   8,   4,  -3,   9,   5,
         8,   5,  -7,  -6,   7,  -4,   2,   5,  -5,   2,  -6,   9,   3,
         7,  -8,   3,  -4,   9,   0,  -1,  -6,  -7,   4,  -5,  -8,  -5,
         1,   8,   5,   6, -10,   2,  -4,   9,   1,   3,  -8,   4,   0,
         3,   5,   4,   6,   7,   1,  -3,  -6,   4,   7,  -3,   8,   1,
         3,  -2,  -2,   6,   1,  -1,  -1, -10,   7,  -5,  -6,  -3,  -1,
        -8,  -1,  -2,  -9,  -3,   0,   5,   7,  -9,  -3,  -2,  -6,  -3,
        -4,  -2,  -5,  -7,   7,   6,   5,   1,  -7,   3, -10,   5,  -5,
         7,   1,  -5,   4,   4,   1,  -4, -10,   9,   0,   0,  -3,   8,
         4,  -9,   0,  -5,   2,  -1,  -9,   2,  -6,  -1,   6,  -6,  -1,
        -3,   2,   8,  -8,  -8,   4,  -1,   8,   2,   6,  -2,   9,   4,
         6,   9,  -2,  -2,   4,  -3,   5,   1,  -5,  -4,   8,   

#### Resize it as a 5x70 matrix Is there a problem? If there is, correct it.

We check what dimension our array has:

In [3]:
array.shape

(450,)

In [4]:
matrix = array.reshape(5,90)
matrix

array([[ -7,   9,  -3,  -7,   5,   0,   9,   2,   7,   9,   9,   4,   7,
          0,  -1,   2,  -3,  -1,  -6,  -7,  -2,  -1,  -3,  -4,   6,   3,
         -5,   7,  -1,  -5,  -8,  -7,  -8, -10,   8,   4,  -3,   9,   5,
          8,   5,  -7,  -6,   7,  -4,   2,   5,  -5,   2,  -6,   9,   3,
          7,  -8,   3,  -4,   9,   0,  -1,  -6,  -7,   4,  -5,  -8,  -5,
          1,   8,   5,   6, -10,   2,  -4,   9,   1,   3,  -8,   4,   0,
          3,   5,   4,   6,   7,   1,  -3,  -6,   4,   7,  -3,   8],
       [  1,   3,  -2,  -2,   6,   1,  -1,  -1, -10,   7,  -5,  -6,  -3,
         -1,  -8,  -1,  -2,  -9,  -3,   0,   5,   7,  -9,  -3,  -2,  -6,
         -3,  -4,  -2,  -5,  -7,   7,   6,   5,   1,  -7,   3, -10,   5,
         -5,   7,   1,  -5,   4,   4,   1,  -4, -10,   9,   0,   0,  -3,
          8,   4,  -9,   0,  -5,   2,  -1,  -9,   2,  -6,  -1,   6,  -6,
         -1,  -3,   2,   8,  -8,  -8,   4,  -1,   8,   2,   6,  -2,   9,
          4,   6,   9,  -2,  -2,   4,  -3,   5,   1,  -

In [5]:
matrix.shape

(5, 90)

#### Get the positive numbers from that matrix using boolean indexing

In [6]:
matrix>0

array([[False,  True, False, False,  True, False,  True,  True,  True,
         True,  True,  True,  True, False, False,  True, False, False,
        False, False, False, False, False, False,  True,  True, False,
         True, False, False, False, False, False, False,  True,  True,
        False,  True,  True,  True,  True, False, False,  True, False,
         True,  True, False,  True, False,  True,  True,  True, False,
         True, False,  True, False, False, False, False,  True, False,
        False, False,  True,  True,  True,  True, False,  True, False,
         True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True, False, False,  True,  True, False,  True],
       [ True,  True, False, False,  True,  True, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False, False, False,
        False, False, False, False,  True,  True,  True,  True, False,
     

In [7]:
matrix[matrix>0]

array([9, 5, 9, 2, 7, 9, 9, 4, 7, 2, 6, 3, 7, 8, 4, 9, 5, 8, 5, 7, 2, 5,
       2, 9, 3, 7, 3, 9, 4, 1, 8, 5, 6, 2, 9, 1, 3, 4, 3, 5, 4, 6, 7, 1,
       4, 7, 8, 1, 3, 6, 1, 7, 5, 7, 7, 6, 5, 1, 3, 5, 7, 1, 4, 4, 1, 9,
       8, 4, 2, 2, 6, 2, 8, 4, 8, 2, 6, 9, 4, 6, 9, 4, 5, 1, 8, 6, 8, 1,
       5, 2, 4, 3, 2, 9, 8, 6, 1, 6, 1, 9, 3, 1, 3, 8, 2, 3, 6, 3, 5, 3,
       2, 4, 6, 7, 3, 9, 2, 5, 5, 2, 8, 7, 8, 9, 5, 5, 4, 9, 2, 8, 2, 1,
       1, 9, 3, 5, 4, 8, 4, 8, 7, 7, 6, 8, 7, 7, 6, 2, 6, 9, 9, 7, 4, 4,
       6, 1, 9, 5, 9, 9, 4, 6, 8, 9, 8, 6, 7, 8, 8, 1, 5, 6, 5, 7, 4, 4,
       2, 6, 4, 8, 1, 9, 9, 6, 6, 4, 9, 1, 6, 5, 6, 6, 5, 6, 3, 8, 8, 1,
       7, 3, 6, 1, 6, 4, 6, 4, 1, 2, 2, 9, 3, 8])

#### Obtain with a function the non-duplicated data

In [8]:
# Example of set
L = [1,1,2]
type(L)

list

In [9]:
set(L)

{1, 2}

In [10]:
# transformation back to list
L = list(set(L))
L

[1, 2]

In [11]:
# array -> list -> set
array = list(array)
array = set(array)

array

{-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [12]:
# set -> list -> array
array = list(array)
array = np.array(array)

array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  -9, -10,  -1,
        -8,  -7,  -6,  -5,  -4,  -3,  -2])

In a line of code:

In [13]:
no_duplicados = np.array(list(set(array)))
no_duplicados

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -1,  -2])

#### On the non-duplicated data, obtain the mean and quartiles.

In [14]:
# we use the mean function
np.mean(no_duplicados)

-0.5

In [15]:
# percentiles
np.percentile(no_duplicados, 25)

-5.25

#### For this array of non-duplicated elements, add a unit to each element.

In [16]:
x = np.array([-5,6,-7,9])
print(np.absolute(x)) #Abs

[5 6 7 9]


#### Create a diagonal matrix

In [17]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [18]:
np.zeros((3,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Equally divide into n spaces

In [19]:
x = np.linspace(1,2,5)
x

array([1.  , 1.25, 1.5 , 1.75, 2.  ])